$engine: 3
$onesync: on
name: CFX Default
version: 3.3.0
author: Tabarra
description: Recipe for the base resources required to run a minimal FiveM server.

tasks: 
  # Download default CFX resources
  - action: download_github
    src: https://github.com/citizenfx/cfx-server-data
    ref: master
    subpath: resources
    dest: ./resources

  - action: download_github
    src: https://github.com/rhscloud/D-Loading
    ref: master
    subpath: resources
    dest: ./resources
    
  # Download default server.cfg
  - action: download_file
    url: https://raw.githubusercontent.com/tabarra/CFX-Default-recipe/main/server.cfg
    path: ./server.cfg
