name: CFX Default
version: 1.0.1
author: Tabarra
description: |-
    Recipe for the base resources required to run a server.

tasks: 
    - action: download_file
      url: https://github.com/citizenfx/cfx-server-data/archive/88f4f974b855e0bf2ca5f51b9916648bd5b7d44b.zip
      path: ./tmp/cfx-server-data.zip

    - action: unzip
      src: ./tmp/cfx-server-data.zip
      dest: ./tmp

    - action: move_path
      src: ./tmp/cfx-server-data-88f4f974b855e0bf2ca5f51b9916648bd5b7d44b/resources
      dest: ./resources

    - action: download_file
      url: https://raw.githubusercontent.com/tabarra/txAdmin-recipes/bbaf78c04b0cd1cff3a2b9c8a48834dfe8eeea7d/cfx_default/server.cfg
      path: ./server.cfg

    - action: remove_path
      path: ./tmp
